# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NJFX', '0002_auto_20180122_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='srfx',
            name='xyck',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=''),
        ),
    ]
