# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NJFX', '0003_srfx_xyck'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='srfx',
            unique_together=set([('jsrq', 'zh', 'xm')]),
        ),
    ]
