# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NJFX', '0004_auto_20180122_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tzqkfx',
            name='bnsyl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u672c\u671f\u6536\u76ca\u7387'),
        ),
        migrations.AlterField(
            model_name='tzqkfx',
            name='gdlsrzb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u56fa\u5b9a\u7c7b-\u6bd4\u5217'),
        ),
        migrations.AlterField(
            model_name='tzqkfx',
            name='gpzb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u6743\u76ca\u7c7b-\u80a1\u7968\u6bd4\u5217'),
        ),
        migrations.AlterField(
            model_name='tzqkfx',
            name='hblsrzb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u8d27\u5e01\u7c7b-\u6bd4\u5217'),
        ),
        migrations.AlterField(
            model_name='tzqkfx',
            name='jz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u57fa\u51c6\u7387'),
        ),
        migrations.AlterField(
            model_name='tzqkfx',
            name='qylsrzb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u6743\u76ca\u7c7b-\u6bd4\u5217'),
        ),
        migrations.AlterField(
            model_name='tzqkfx',
            name='rq',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='tzqkfx',
            name='zhmc',
            field=models.CharField(blank=True, choices=[('\u56fd\u5bff', '\u56fd\u5bff'), ('\u957f\u6c5f', '\u957f\u6c5f'), ('\u957f\u6c5f2', '\u957f\u6c5f2'), ('\u4e2d\u4fe1', '\u4e2d\u4fe1'), ('\u534e\u590f', '\u534e\u590f'), ('\u4e2d\u91d1', '\u4e2d\u91d1'), ('\u4e2d\u91d12', '\u4e2d\u91d12'), ('\u4e2d\u91d1\u4fe1\u6258', '\u4e2d\u91d1\u4fe1\u6258'), ('\u4e2d\u91d1\u5408\u5e76', '\u4e2d\u91d1\u5408\u5e76'), ('\u5de5\u94f6', '\u5de5\u94f6'), ('\u592a\u5e73', '\u592a\u5e73'), ('\u592a\u5e732', '\u592a\u5e732'), ('\u592a\u5e73\u4fe1\u6258', '\u592a\u5e73\u4fe1\u6258'), ('\u592a\u5e73\u5408\u5e76', '\u592a\u5e73\u5408\u5e76'), ('\u6cf0\u5eb7', '\u6cf0\u5eb7'), ('\u6cf0\u5eb72', '\u6cf0\u5eb72'), ('\u6cf0\u5eb73', '\u6cf0\u5eb73'), ('\u6cf0\u5eb7\u5408\u5e76', '\u6cf0\u5eb7\u5408\u5e76'), ('\u535a\u65f6', '\u535a\u65f6'), ('\u5609\u5b9e', '\u5609\u5b9e'), ('\u6cf0\u5eb74', '\u6cf0\u5eb74'), ('\u5e73\u5b89', '\u5e73\u5b89'), ('\u5e73\u5b892', '\u5e73\u5b892'), ('\u5e73\u5b89\u5408\u5e76', '\u5e73\u5b89\u5408\u5e76'), ('\u53d7\u6258\u6237', '\u53d7\u6258\u6237'), ('\u957f\u6c5f\u9000\u4f11', '\u957f\u6c5f\u9000\u4f11'), ('\u957f\u6c5f\u9000\u4f112', '\u957f\u6c5f\u9000\u4f112'), ('\u9000\u4f11\u5408\u5e76', '\u9000\u4f11\u5408\u5e76'), ('\u672c\u671f\u7d2f\u8ba1', '\u672c\u671f\u7d2f\u8ba1'), ('\u672c\u671f\u53d8\u52a8', '\u672c\u671f\u53d8\u52a8'), ('\u4e0a\u671f\u7d2f\u8ba1', '\u4e0a\u671f\u7d2f\u8ba1'), ('\u8ba1\u5212', '\u8ba1\u5212'), ('\u672c\u671f\u589e\u51cf\u53d8\u52a8', '\u672c\u671f\u589e\u51cf\u53d8\u52a8')], max_length=15, null=True, verbose_name='\u7ec4\u5408'),
        ),
    ]
