# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NJFX', '0006_zczd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gyfx',
            old_name='zh',
            new_name='zhmc',
        ),
        migrations.RenameField(
            model_name='srfx',
            old_name='zh',
            new_name='zhmc',
        ),
        migrations.RenameField(
            model_name='ta',
            old_name='zh',
            new_name='zhmc',
        ),
        migrations.RenameField(
            model_name='wdcp',
            old_name='zh',
            new_name='zhmc',
        ),
        migrations.RenameField(
            model_name='zcfbb',
            old_name='zh',
            new_name='zhmc',
        ),
        migrations.RenameField(
            model_name='zcfbbrjcc',
            old_name='zh',
            new_name='zhmc',
        ),
        migrations.RenameField(
            model_name='zcjz',
            old_name='zh',
            new_name='zhmc',
        ),
        migrations.AlterUniqueTogether(
            name='gyfx',
            unique_together=set([('zcmc', 'ksrq', 'zhmc', 'zclb')]),
        ),
        migrations.AlterUniqueTogether(
            name='srfx',
            unique_together=set([('jsrq', 'zhmc', 'xm')]),
        ),
        migrations.AlterUniqueTogether(
            name='ta',
            unique_together=set([('rq', 'zhmc', 'jzrq')]),
        ),
        migrations.AlterUniqueTogether(
            name='zcfbb',
            unique_together=set([('rq', 'zhmc', 'zcmc', 'zclb')]),
        ),
        migrations.AlterUniqueTogether(
            name='zcfbbrjcc',
            unique_together=set([('jsrq', 'zhmc', 'zcmc', 'zclb')]),
        ),
        migrations.AlterUniqueTogether(
            name='zcjz',
            unique_together=set([('rq', 'zhmc')]),
        ),
    ]
