# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NJFX', '0007_auto_20180131_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gyfx',
            options={'verbose_name': '归因分析表', 'verbose_name_plural': '归因分析表'},
        ),
        migrations.AlterModelOptions(
            name='zcfbb',
            options={'verbose_name': '资产分布表', 'verbose_name_plural': '资产分布表'},
        ),
        migrations.AlterField(
            model_name='gyfx',
            name='jsrq',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='gyfx',
            name='ksrq',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='gyfx',
            name='zclb',
            field=models.CharField(max_length=30, verbose_name='资产类别'),
        ),
        migrations.AlterField(
            model_name='gyfx',
            name='zcmc',
            field=models.CharField(max_length=50, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='gyfx',
            name='zhmc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='组合名称'),
        ),
    ]
